config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users do
    resources :user_locations
  end
  resources :cabs do
    resources :cab_locations
  end

  root 'cab_locations#index'

end

app/models/cab.rb
class Cab < ActiveRecord::Base
	has_many :cab_locations
	with_options presence: true do |assoc|
		assoc.validates :driver_name
		assoc.validates :taxi_number
	end

	
end

app/models/cab_location.rb
class CabLocation < ActiveRecord::Base
  	belongs_to :cab
  	with_options presence: true do |assoc|
		assoc.validates :longitude
		assoc.validates :latitude
		assoc.validates :cab_id
	end
	def self.get_nearest_cabs(user_location)
		self.find_by_sql("select * from cab_locations where SQRT(Power(? - latitude, 2) + Power(? - longitude, 2)) limit 10",user_location.latitude, user_location.longitude )
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_locations, inverse_of: :user
	with_options presence: true do |assoc|
		assoc.validates :name
		assoc.validates :email
	end
end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user, inverse_of: :user_locations
  with_options presence: true do |assoc|
		assoc.validates :longitude
		assoc.validates :latitude
		assoc.validates :user_id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cab_locations_controller.rb
class CabLocationsController < ApplicationController
  before_action :set_cab_location, only: [:show, :edit, :update, :destroy]

  # GET /cab_locations
  # GET /cab_locations.json
  def index
    @cab_locations = CabLocation.all
  end

  # GET /cab_locations/1
  # GET /cab_locations/1.json
  def show
  end

  # GET /cab_locations/new
  def new
    @cab_location = CabLocation.new
  end

  # GET /cab_locations/1/edit
  def edit
  end

  # POST /cab_locations
  # POST /cab_locations.json
  def create
    @cab_location = CabLocation.new(cab_location_params)

    respond_to do |format|
      if @cab_location.save
        format.html { redirect_to @cab_location, notice: 'Cab location was successfully created.' }
        format.json { render :show, status: :created, location: @cab_location }
      else
        format.html { render :new }
        format.json { render json: @cab_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cab_locations/1
  # PATCH/PUT /cab_locations/1.json
  def update
    respond_to do |format|
      if @cab_location.update(cab_location_params)
        format.html { redirect_to @cab_location, notice: 'Cab location was successfully updated.' }
        format.json { render :show, status: :ok, location: @cab_location }
      else
        format.html { render :edit }
        format.json { render json: @cab_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cab_locations/1
  # DELETE /cab_locations/1.json
  def destroy
    @cab_location.destroy
    respond_to do |format|
      format.html { redirect_to cab_locations_url, notice: 'Cab location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cab_location
      @cab_location = CabLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cab_location_params
      params.require(:cab_location).permit(:longitude, :latitude, :cab_id)
    end
end

app/controllers/cabs_controller.rb
class CabsController < ApplicationController
  before_action :set_cab, only: [:show, :edit, :update, :destroy]

  # GET /cabs
  # GET /cabs.json
  def index
    @cabs = Cab.all
  end

  # GET /cabs/1
  # GET /cabs/1.json
  def show
  end

  # GET /cabs/new
  def new
    @cab = Cab.new
  end

  # GET /cabs/1/edit
  def edit
  end

  # POST /cabs
  # POST /cabs.json
  def create
    @cab = Cab.new(cab_params)

    respond_to do |format|
      if @cab.save
        format.html { redirect_to @cab, notice: 'Cab was successfully created.' }
        format.json { render :show, status: :created, location: @cab }
      else
        format.html { render :new }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabs/1
  # PATCH/PUT /cabs/1.json
  def update
    respond_to do |format|
      if @cab.update(cab_params)
        format.html { redirect_to @cab, notice: 'Cab was successfully updated.' }
        format.json { render :show, status: :ok, location: @cab }
      else
        format.html { render :edit }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabs/1
  # DELETE /cabs/1.json
  def destroy
    @cab.destroy
    respond_to do |format|
      format.html { redirect_to cabs_url, notice: 'Cab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cab
      @cab = Cab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cab_params
      params.require(:cab).permit(:driver_name, :taxi_number)
    end
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  before_action :fetch_user
  before_action :fetch_cabs, only: [:index]
  def new
    @user_location=UserLocation.new
  end

  def create
    @user_location=UserLocation.new(user_params)
    respond_to do |format|
      if @user_location.save
        format.html { redirect_to user_user_locations_path, notice: 'Cab location was successfully created.' }
        format.json { render :show, status: :created, location: @user_location }
      else
        format.html { render :new }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @userlocations=@user.user_locations
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private
  def fetch_cabs
    @nearest_cabs=CabLocation.get_nearest_cabs(@user_location)
  end
  def fetch_user
    @user=User.find_by_id(params[:user_id])
  end
  def user_params
    params.require(:user_location).permit(:longitude, :latitude, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @users=User.all
  end

  def update
  end

  def edit
  end

  def destroy
  end
  def show
  end
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cab_locations_helper.rb
module CabLocationsHelper
end

app/helpers/cabs_helper.rb
module CabsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_location_helper.rb
module UserLocationHelper
end

app/views/cab_locations/_form.html.erb
<%= form_for(@cab_location) do |f| %>
  <% if @cab_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cab_location.errors.count, "error") %> prohibited this cab_location from being saved:</h2>

      <ul>
      <% @cab_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :cab_id %><br>
    <%= f.text_field :cab_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cab_locations/edit.html.erb
<h1>Editing Cab Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @cab_location %> |
<%= link_to 'Back', cab_locations_path %>

app/views/cab_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cab Locations</h1>

<table>
  <thead>
    <tr>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Cab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cab_locations.each do |cab_location| %>
      <tr>
        <td><%= cab_location.longitude %></td>
        <td><%= cab_location.latitude %></td>
        <td><%= cab_location.cab %></td>
        <td><%= link_to 'Show', cab_location %></td>
        <td><%= link_to 'Edit', edit_cab_location_path(cab_location) %></td>
        <td><%= link_to 'Destroy', cab_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cab location', new_cab_location_path %>

app/views/cab_locations/new.html.erb
<h1>New Cab Location</h1>

<%= render 'form' %>

<%= link_to 'Back', cab_cab_locations_path %>

app/views/cab_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Longitude:</strong>
  <%= @cab_location.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @cab_location.latitude %>
</p>

<p>
  <strong>Cab:</strong>
  <%= @cab_location.cab %>
</p>

<%= link_to 'Edit', edit_cab_location_path(@cab_location) %> |
<%= link_to 'Back', cab_locations_path %>

app/views/cabs/_form.html.erb
<%= form_for(@cab) do |f| %>
  <% if @cab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cab.errors.count, "error") %> prohibited this cab from being saved:</h2>

      <ul>
      <% @cab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :driver_name %><br>
    <%= f.text_field :driver_name %>
  </div>
  <div class="field">
    <%= f.label :taxi_number %><br>
    <%= f.text_field :taxi_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabs/edit.html.erb
<h1>Editing Cab</h1>

<%= render 'form' %>

<%= link_to 'Show', @cab %> |
<%= link_to 'Back', cabs_path %>

app/views/cabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cabs</h1>

<table>
  <thead>
    <tr>
      <th>Driver name</th>
      <th>Taxi number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabs.each do |cab| %>
      <tr>
        <td><%= cab.driver_name %></td>
        <td><%= cab.taxi_number %></td>
        <td><%= link_to 'Show', cab %></td>
        <td><%= link_to 'Edit', edit_cab_path(cab) %></td>
        <td><%= link_to 'Destroy', cab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cab', new_cab_path %>

app/views/cabs/new.html.erb
<h1>New Cab</h1>

<%= render 'form' %>

<%= link_to 'Back', cabs_path %>

app/views/cabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driver name:</strong>
  <%= @cab.driver_name %>
</p>

<p>
  <strong>Taxi number:</strong>
  <%= @cab.taxi_number %>
</p>
<p>
	<%= link_to 'Add Cabs Locations', new_cab_cab_location_path(@cab)%>
</p>

<%= link_to 'Edit', edit_cab_path(@cab) %> |
<%= link_to 'Back', cabs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxiService</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_locations/_form.html.erb
<%= form_for @user_location, url: user_user_locations_path do |f| %>
  <% if @user_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
      <% @user_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_locations/create.html.erb
<h1>UserLocation#create</h1>
<p>Find me in app/views/user_location/create.html.erb</p>

app/views/user_locations/destroy.html.erb
<h1>UserLocation#destroy</h1>
<p>Find me in app/views/user_location/destroy.html.erb</p>

app/views/user_locations/edit.html.erb
<h1>UserLocation#edit</h1>
<p>Find me in app/views/user_location/edit.html.erb</p>

app/views/user_locations/index.html.erb
<h1>Listing UserLocation</h1>

<table>
  <thead>
    <tr>
      <th>Driver name</th>
      <th>Taxi number</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @userlocations.map do |user_location| %>
      <tr>
        <td><%= user_location.longitude %></td>
        <td><%= user_location.latitude %></td>
        <td><%= user_location.user.name%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_locations/new.html.erb
<h1> Enter your location and book your cab</h1>

<%= render 'form' %>

<%= link_to 'Back', user_user_locations_path %>

app/views/user_locations/update.html.erb
<h1>UserLocation#update</h1>
<p>Find me in app/views/user_location/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cabs</h1>

<table>
  <thead>
    <tr>
      <th>Driver name</th>
      <th>Taxi number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
        <td><%= link_to 'Book a cab', new_user_user_location_path(user)%></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>